### ISSUE TITLE
test_issue

### ISSUE THREAD

**Issue by Schantzl** [legokor/SmartHome_WebApp#1]
implement something

**Comment by Schantzl** [comment]
dikk micsoda issuing :D

**Comment by HangFalx** [comment]
Azt a mindenit

**Comment by Schantzl** [comment]
that's done

**Comment by MoriczTamas** [comment]
Szerintem ez még nincs kész. #adminpowers

**Comment by Schantzl** [comment]
dehogy is nem de úgy ám de készen van!
